name: CI/CD

on: push

jobs:
  pdf:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # Download latest version of https://github.com/roquec/resume
      - name: Checkout resume repository
        uses: actions/checkout@v4
      # Generate PDF from resume.md file
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: src/resume.md
          output_dir: src
          build_html: true
      # Commit resume.pdf file back into repository
      - uses: stefanzweifel/git-auto-commit-action@v5