name: CI/CD

on: push

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Download latest version of https://github.com/roquec/resume
      - name: Checkout resume repository
        uses: actions/checkout@v4
      # Generate PDF from resume.md file
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: ./src/resume.md
          output_dir: ./output/
          theme: ./src/styles.css
          build_html: true
      # Commit resume.pdf file back into repository
      - name: Commit PDF file into repository
        uses: stefanzweifel/git-auto-commit-action@v5
      # Execute script to add a content hash to all asset links in generated site
      - name: Copy HTML file into '_site' folder
        run: |
          mkdir -p ./_site
          cp ./output/resume.html ./_site/index.html
          cp ./output/resume.pdf ./_site/roque-carrizo-resume.pdf
      # Upload generated site as an artifact so the following jobs can access it
      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Configure and enable GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      # Publish website content from github-pages artifact to our GitHub Pages environment
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}